stages:
  - deploy

# Définition du job "deploy"
Deploiement:
  stage: deploy
  # Spécification du runner
  tags:
    - shell

  # Définition des étapes du job
  script:
    - apt-get update && apt-get install -y git  # Installation de Git
    - (cd ~/Cube-3-back/ && git pull --rebase) || ( cd ~/ && git clone $CI_PROJECT_URL)  # Clonage du projet
    - cd ~/Cube-3-back/ && docker compose down && docker compose up
  when: manual