version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./:/back
  postgres:
    image: postgres:9.6
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
# POUR LA MEMOIRE EN CACHE
  redis:
    image: redis:3.2.10
